administrator/urls.py
from django.urls import path
from . import views

app_name = "administrator"


urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path("students/", views.StudentListView.as_view(), name="student-list"),
    path('students/create/', views.create_student, name="create-student"),
    path('teachers/', views.TeacherListView.as_view(), name="teacher-list"),
    path('teachers/create/', views.create_teacher, name="create-teacher"),
    path('student/<int:id>/profile/', views.student_profile, name="student-profile"),
    path('teacher/<int:id>/profile/', views.teacher_profile, name="teacher-profile"),
    path('classes/create/', views.create_klass, name="create-class"),
    path('classes/list/', views.KlassListview.as_view(), name="class-list"),
    path('classes/list/<int:pk>', views.KlassDetailView.as_view(), name="class-detail"),
    path('classes/list/<int:pk>/add-students/', views.add_students_to_class, name="add-students-to-class"),
    path('classes/list/<int:pk>/add-teacherss/', views.add_teachers_to_class, name="add-teachers-to-class"),
    path('academic-year/', views.AcademicYearListView.as_view(), name="academic-year-list"),
    path('academic-year/create/', views.create_academic_year, name="create-academic-year"),
    path('academic-year/<int:pk>/', views.AcademicYearDetailView.as_view(), name="academic-year-detail"),
    path('course/create/', views.create_course, name="create-course"),
    path('couerse/list/', views.CoursetListView.as_view(), name="course-list"),
    path('notice/create/', views.create_notice, name="create-notice"),
    path('notice/delete/<int:id>/', views.delete_notice_item, name="delete-notice-item"),

]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('django-unicorn', include('django_unicorn.urls', namespace="django_unicorn")),
    path('accounts/', include('accounts.urls',  namespace="accounts")),
    path('accounts/default/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),

    path('', include('pages.urls')),
    path('administrator/', include('administrator.urls', namespace="administrator")),
]

urlpatterns = urlpatterns + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include(debug_toolbar.urls)),
    )

pages/urls.py
from django.urls import path

from .views import HomePageView, AboutPageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about/', AboutPageView.as_view(), name='about'),
]

administrator/forms.py
from django.db.models.query_utils import Q
from accounts.models import AcademicYear, Klass, Student
from accounts.models import Klass, Course, NoticeBoard
from django import forms
from django.contrib.auth import get_user_model
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Column, Row

# Get the authentication class
User = get_user_model()


class StudentCreateForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    date_of_birth = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}))

    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "password",
            "picture",
            "date_of_birth",
            "sex",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column(
                Row(
                    Column("username", css_class="col-sm-6 col-md-4"),
                    Column("email", css_class="col-sm-6 col-md-4"),
                    Column("password", css_class="col-sm-12 col-md-4"),
                ),
                css_class="shadow my-3 p-3",
            ),
            Column(
                Row(
                    Column("first_name", css_class="col-sm-6"),
                    Column("last_name", css_class="col-sm-6"),
                    Column("date_of_birth", css_class="col-12"),
                ),
                css_class="shadow p-3 my-3",
            ),
            Column(
                Row(
                    Column("picture", css_class="col-sm-6"),
                    Column("sex", css_class="col-sm-6"),
                ),
                css_class="shadow p-3 my-3",
            ),
        )
        self.helper.form_tag = False

    def save(self,is_student=True, commit=True, *args, **kwargs):
        student = super(StudentCreateForm, self).save(commit=False*args, **kwargs)
        student.set_password(self.cleaned_data["password"])
        if is_student:
            student.is_student = True
            if commit:
                student.save()
        return student


class TeacherCreateForm(StudentCreateForm):
    def save(self, commit=True, *args, **kwargs):

        teacher = super(TeacherCreateForm, self).save(is_student=False, commit=False, *args, **kwargs)
        teacher.is_teacher = True
        if commit:
            teacher.save()
        return teacher


class KlassCreateForm(forms.ModelForm):

    class Meta:
        model = Klass
        fields = ("klass_name", 'academic_year')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column("klass_name"),
            Column("academic_year")
        
        )
        self.helper.form_tag = False

class AcademicYearForm(forms.ModelForm):
    
    start_year = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}))
    end_year = forms.DateField(required=False, widget=forms.DateInput(attrs={"type": "date"}))
    class Meta:
        model = AcademicYear
        fields = '__all__'


class AddStudentToClassForm(forms.Form):
    students = forms.ModelMultipleChoiceField(queryset=Student.objects.all())

    def __init__(self, data=None, klass=None,*args, **kwargs, ) -> None:
        super().__init__(data=data, *args, **kwargs)
        students = Student.objects.filter(is_active=True).exclude(klasses__is_active=True)
        if klass:
            students = students.exclude(klasses=klass)
        self.fields['students'].queryset = students
        self.helper = FormHelper()
        self.helper.layout = Layout('students')
            
        self.helper.form_tag = False

class CourseCreateForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ("klass", "name", "description", "teacher",)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column("klass"),
            Column("teacher"),
            Column(
                Row(
                    Column("name", css_class="col-sm-6"),
                    Column("description", css_class="col-sm-6 "),
                ),
            ),
        )
        self.helper.form_tag = False

class CreateNoticeForm(forms.ModelForm):
    date = forms.DateField(widget=forms.DateInput(attrs={"type": "date"}), required=False)

    class Meta:
        model = NoticeBoard
        fields = ("title", "content", "date",)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column("title"),
            Column("content"),
            Column("date"),
        )
        self.helper.form_tag = False


class AddTeacherToClassForm(forms.ModelForm):
    class Meta:
        model = Klass
        fields = ("teachers",)

administrator/views.py
from accounts.models import AcademicYear, Klass
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .utils import administrator_required
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from . import forms
from django.views.generic import ListView, TemplateView, CreateView, DetailView
from django.contrib.auth import get_user_model

from accounts.models import Student, Teacher, Course, NoticeBoard
from datetime import datetime
# Create your views here.

User = get_user_model()

@login_required
@administrator_required
def dashboard(request):
    return render(request, 'administrator/dashboard.html', {
        'teachers': User.objects.filter(is_teacher=True),
        'students': User.objects.filter(is_student=True),
        'notices': NoticeBoard.objects.all(),
    })

class StudentListView(TemplateView):
    template_name = "administrator/student_list.html"

class TeacherListView(TemplateView):
    template_name = "administrator/teacher_list.html"

@login_required
@administrator_required
def create_student(request):
    if request.method == "POST":
        student_form = forms.StudentCreateForm(request.POST, files=request.FILES)
        if student_form.is_valid():
            student = student_form.save()
            messages.success(request, f'Student: {student.username} created successfully')
            return redirect("administrator:dashboard")
        messages.error(request, "Unable to create student, please try again")
    else:
        student_form = forms.StudentCreateForm()
    return render(request, 'administrator/create_student.html', {'student_form': student_form})

@login_required
@administrator_required
def create_teacher(request):
    if request.method == "POST":
        teacher_form = forms.TeacherCreateForm(request.POST, files=request.FILES)
        if teacher_form.is_valid():
            teacher = teacher_form.save()
            messages.success(request, f'Student: {teacher.username} created successfully')
            return redirect("administrator:dashboard")
        messages.error(request, "Unable to create teacher, please try again")
    else:
        teacher_form = forms.TeacherCreateForm()
    return render(request, 'administrator/create_teacher.html', {'teacher_form': teacher_form})

@login_required
@administrator_required
def student_profile(request, id):
    student = get_object_or_404(Student, user__id=id)
    age = int((datetime.now().date() - student.user.date_of_birth).days / 365 )
    return render(request, 'administrator/student_profile.html', {'student':student,'age':age,})

@login_required
@administrator_required
def teacher_profile(request, id):
    teacher = get_object_or_404(Teacher, user__id=id)
    age = int((datetime.now().date() - teacher.user.date_of_birth).days / 365 )
    return render(request, 'administrator/teacher_profile.html', {'teacher':teacher,'age':age})

def create_academic_year(request: HttpRequest):
    if request.method == "POST":
        academic_year_form = forms.AcademicYearForm(request.POST)
        if academic_year_form.is_valid():
            academic_year = academic_year_form.save()
            return redirect(academic_year.get_admin_absolute_url())
    else:
        academic_year_form = forms.AcademicYearForm()
    return render(request, "administrator/create_academic_year.html", {'form': academic_year_form})
""" class SubjectList(ListView):
    model = Course
    template_name = 'administration/subject_list.html'
    context_object_name = 'subjects' """

class AcademicYearListView(ListView):
    model = AcademicYear
    context_object_name = "academic_years"
    template_name = "administrator/academic_year_list.html"


class AcademicYearDetailView(DetailView):
    model = AcademicYear
    context_object_name = "academic_year"
    template_name = "administrator/academic_year_detail.html"



def create_klass(request: HttpRequest, *args, **kwargs) -> HttpResponse:
    if request.method == "POST":
        form = forms.KlassCreateForm(request.POST, files=request.FILES)
        if form.is_valid():
            klass = form.save()
            return redirect("administrator:dashboard")
        else:
            print("Form is invalid\n\n\n\n")
            print(form.errors)
    else:
        form = forms.KlassCreateForm()
    return render(request, 'administrator/create_class.html', {'form': form})

class KlassListview(ListView):
    model = Klass
    template_name = "administrator/class_list.html"
    context_object_name = "classes"

    def qet_queryset(self, *args, **kwargs):
        return Klass.objects.filter(academic_year__is_active=True)

class KlassDetailView(DetailView):
    model = Klass
    template_name = "administrator/klass_detail.html"
    context_object_name = "klass"

def add_students_to_class(request: HttpRequest, pk:int):
    klass = get_object_or_404(Klass, pk=pk, academic_year__is_active=True)
    if request.method == "POST":
        students_form = forms.AddStudentToClassForm(request.POST, klass=klass)
        if students_form.is_valid():
            cd = students_form.cleaned_data
            # TODO: this is too slow O(n)
            for student in cd['students']:
                student.klasses.add(klass)
            # a faster version is 
            # klass.students.add(*cd['students'])
            # but it keeps raising contraint errors.

            return redirect(klass.get_admin_absolute_url())
    else:
        students_form = forms.AddStudentToClassForm(klass=klass)
    return render(request, "administrator/add_student_to_class.html", {'form': students_form, 'klass': klass})

@administrator_required
def add_teachers_to_class(request: HttpRequest, pk:int):
    klass = get_object_or_404(Klass, pk=pk, academic_year__is_active=True)
    if request.method == "POST":
        teacher_form = forms.AddTeacherToClassForm(request.POST, instance=klass)
        
        if teacher_form.is_valid():
            teacher_form.save()

            return redirect(klass.get_admin_absolute_url())
    else:
        teacher_form = forms.AddTeacherToClassForm(instance=klass)
    return render(request, "administrator/add_teacher_to_class.html", {'form': teacher_form, 'klass': klass})
    
def create_course(request):
    if request.method == "POST":
        form = forms.CourseCreateForm(request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect("administrator:dashboard")
    else:
        form = forms.CourseCreateForm()
    return render(request, 'administrator/create_course.html', {'form': form})


class CoursetListView(ListView):
    model = Course
    template_name = 'administrator/course_list.html'
    context_object_name = 'courses'

    def get_queryset(self, *args, **kwargs):
        return Course.objects.all()


def create_notice(request):
    if request.method == "POST":
        form = forms.CreateNoticeForm(request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect("administrator:dashboard")
    else:
        form = forms.CreateNoticeForm()
    return render(request, 'administrator/create_notice.html', {'form':form})

def delete_notice_item(request, id):
    notice = get_object_or_404(NoticeBoard, id=id)
    notice.delete()
    return redirect("administrator:dashboard")

administrator/templates/administrator/academic_year_detail.html
{% extends '_base_dashboard.html' %}

{% load unicorn %}
{% load crispy_forms_tags %}

{% block dashboard_content %}
{% load unicorn %}

<div class="container-fluid">
    <div class="container-fluid">
        <a href="{% url 'administrator:create-student' %}">
            <div class=" m-0 info-color shadow btn btn-primary w-100 white-text text-center py-4">
                <i class="fas fa-plus-circle mr-4"></i> {{ academic_year }}
            </div>
        </a>
    </div>
    <div class="container-fluid">
        <div class="row">
            {% for klass in academic_year.klasses.all %}
            <div class="col-md-6 col-lg-4 py-4">
                <a href="{{ klass.get_admin_absolute_url }}">
                    <div class="shadow p-4 bg-white">
                        <p class="m-0 font-weight-bold text-center">{{ klass }}</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>


</div>
{% endblock %}

administrator/templates/administrator/academic_year_list.html
{% extends '_base_dashboard.html' %}

{% load unicorn %}
{% load crispy_forms_tags %}

{% block dashboard_content %}
{% load unicorn %}

<div class="container-fluid">
    <div class="container-fluid">
        <div class=" my-4 info-color shadow btn w-100 white-text text-center bg-white py-4">
            <!-- <i class="fas fa-plus-circle mr-4"> </i>--> ACADEMIC YEARS
        </div>
        <a href="{% url 'administrator:create-academic-year' %}">
            <div class=" m-0 info-color shadow btn btn-primary w-100 white-text text-center py-4">
                <i class="fas fa-plus-circle mr-4"></i> Create New Academic Year
            </div>
        </a>
    </div>
    <div class="container-fluid">
        <div class="row">
            {% for academic_year in academic_years %}
            <div class="col-md-6 col-lg-4 py-4">
                <a href="{{ academic_year.get_admin_absolute_url }}">
                    <div class="shadow p-4 bg-white">
                        <p class="m-0 text-center"><span class="font-weight-bold">{{ academic_year }}</span> academic year.</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>


</div>
{% endblock %}

administrator/templates/administrator/add_student_to_class.html
{% extends '_base_dashboard.html' %}

{% load crispy_forms_tags %}

{% block dashboard_content %}

<div class="container">
    <div class=" m-0 info-color shadow white-text text-center py-4">
        add students to {{ klass }}
    </div>
    <form action="." class="py-3 shadow my-5" method="POST", enctype="multipart/form-data">
        <div class="container">

            {% csrf_token %}
            {% crispy form %}
            <div class="py-3">
                <button type="submit" class="btn btn-lg btn-primary">Add Students</button>
            </div>
        </div>
    </form>


</div>
{% endblock %}

administrator/templates/administrator/add_teacher_to_class.html
{% extends '_base_dashboard.html' %}

{% load crispy_forms_tags %}

{% block dashboard_content %}

<div class="container">
    <div class=" m-0 info-color shadow white-text text-center py-4">
        <h3 class="m-o">Assign Teachers to {{ klass }}</h3>
    </div>
    <form action="." class="py-3 shadow my-5" method="POST", enctype="multipart/form-data">
        <div class="container">

            {% csrf_token %}
            {% crispy form %}
            <div class="py-3">
                <button type="submit" class="btn btn-lg btn-primary">Add Teachers</button>
            </div>
        </div>
    </form>


</div>
{% endblock %}

administrator/templates/administrator/class_list.html
{% extends '_base_dashboard.html' %}
{% load static %}

{% block dashboard_content %}
<div class="row">
    <div class="col-12 cls-btns">
        <a href="{% url 'administrator:create-class' %}">
            <div class=" m-0 info-color shadow btn btn-primary  white-text text-center py-2">
                <i class="fas fa-plus-circle mr-4"></i> Add Class
            </div>
        </a>
        <a href="{% url 'administrator:create-class' %}">
            <div class=" m-0 info-color shadow btn btn-info  white-text text-center py-2">
                <i class="fas fa-plus-circle mr-4"></i> Assign Teacher
            </div>
        </a>
    </div>
    <br>

    {% for class in classes %}
    <div class="col-md-4 col-lg-3 badges">
        <a class="cls shadow p-2  {% cycle 'bg-danger' 'bg-info' 'bg-primary' 'bg-success' 'bg-warning' 'bg-secondary' %}" 
        href="{{ class.get_admin_absolute_url }}">
        <div class="cls-name text-uppercase font-bolder">
            {{ class.klass_name }}
        </div>
            <div class="cls-info">
                <div class="stdnumber mr-2">
                    {{ class.students.count }}
                </div>
                students
            </div>
            <hr>
            <div class="cls-teachers">
                {{ class.teachers.count }} Teachers <span class="ml-3">
                    {{ class.courses.count }} Subjects</span>
            </div>
        </a>
    </div>
    {% endfor %}
</div>

<br>

{% endblock %}

administrator/templates/administrator/course_list.html
{% extends '_base_dashboard.html' %}
{% load static %}

{% block dashboard_content %}
<div class="row">
    <div class="col-12 cls-btns">
        <a href="{% url 'administrator:create-course' %}">
            <div class=" m-0 info-color shadow btn btn-primary  white-text text-center py-2">
                <i class="fas fa-plus-circle mr-4"></i> Add Course
            </div>
        </a>
        <a href="#">
            <div class=" m-0 info-color shadow btn btn-info  white-text text-center py-2">
                <i class="fas fa-plus-circle mr-4"></i> Assign Teacher
            </div>
        </a>
    </div>
    <br>

    <div class="container">
        <!-- put component code here -->
        <div class="mt-4 bg-white p-3 shadow">
            
            <input type="text" unicorn:model.debounce-500="query_string" class="form-control"
                placeholder="Enter Name...">
        </div>
        <div class="py-5">
            <table class="table table-striped shadow bg-white">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Course Name</th>
                        <th>Class</th>
                        <th>No. of Studnets</th>
                        <th>Assigned Teacher</th>
                        <th>Active</th>
                    </tr>
                </thead>
                <tbody>
                    {% for course in courses %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ course.name }}</td>
                        <td>{{ course.klass }}</td>
                        <td>{{ course.students.count }}</td>
                        <td>{{ course.teacher }}</td>
                        <td>{{ course.is_active }}</td>
                        <td>
                            <a href="" class="btn btn-sm btn-info"><i class="fas fa-pen-square"></i></a>
                            <a href="" class="btn btn-sm btn-success"><i class="fas fa-eye"></i></a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="4" class="text-danger  text-center">No Subject.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>

{% endblock %}

administrator/templates/administrator/create_academic_year.html
{% extends '_base_dashboard.html' %}

{% load crispy_forms_tags %}

{% block dashboard_content %}

<div class="container">
    <div class=" m-0 info-color shadow white-text text-center py-4">
        Create New Academic Year
    </div>
    <form action="." class="py-3 shadow my-5" method="POST", enctype="multipart/form-data">
        <div class="container">

            {% csrf_token %}
            {% crispy form %}
            <div class="py-3">
                <button type="submit" class="btn btn-lg btn-primary">Create</button>
            </div>
        </div>
    </form>


</div>
{% endblock %}

administrator/templates/administrator/dashboard.html
{% extends '_base_dashboard.html' %}
{% load static %}
{% load humanize %}

{% block dashboard_content %}
<div class="container ">
    <div class="row">
        <div class="col-sm-6 col-md-4 col-lg-3 badges">
            <a class="badge-content" href="{% url 'administrator:student-list' %}">
                <div class="card-ico">
                    <img class="ico" src="{% static 'images/student_icon.png' %}" alt="nt fnd">
                    <br> Students
                </div>
                <div class="m-3 vertical-line"></div>
                <div class="stdnumber">
                    {{ students.count }}
                </div>
            </a>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-3 badges">
            <a class="badge-content" href="{% url 'administrator:teacher-list' %}">
                <div class="card-ico">
                    <img class="ico" src="{% static 'images/staff_icon.png' %}" alt="nt fnd">
                    <br> Staffs
                </div>
                <div class="m-3 vertical-line"></div>
                <div class="stdnumber">
                    {{ teachers.count }}
                </div>
            </a>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-3 badges">
            <a class="badge-content" href="#">
                <div class="card-ico">
                    <img class="ico" src="{% static 'images/workers_icon.png' %}" alt="nt fnd">
                    <br> Workers
                </div>
                <div class="m-3 vertical-line"></div>
                <div class="stdnumber">
                    100
                </div>
            </a>
        </div>
        <div class="col-sm-6 col-md-4 col-lg-3 badges">
            <a class="badge-content" href="#">
                <div class="card-ico">
                    <!-- <img class="ico" src="{% static 'images/workewrs_icon.png' %}" alt="nt fnd"> -->
                    <i class="far fa-money-bill-alt text-success fa-lg fa-3x"></i>
                    <br> Total Earnigs
                </div>
                <div class="m-3 vertical-line"></div>
                <div class="stdnumber">
                    100
                </div>
            </a>
        </div>
    </div>

    <div class="row mt-3 py-3">
        <div class="col-lg-8 badges">
            <div class="fees-info p-3">
                <div class="fee-text">
                    <i class="fas fa-hand-holding-usd mr-3 text-success"></i> Fees Collection
                    <hr>
                </div>
                <div class="row ml-1">
                    <div class="col-5 text-left fee-collec">
                        <div class="fee-collec d-flex">
                            <i class="fas fa-database text-warning fa-lg mr-2"></i>
                            <div class="">
                                <span class="text-bolder"> $ 300,000.00</span> <br>
                                <span style="font-size: 0.75rem;">Collections</span>
                            </div>
                        </div>
                        <div class="expenses mt-4 d-flex">
                            <i class="fas fa-shopping-cart fa-lg text-danger mr-2"></i>
                            <div class="">
                                <span class="text-bolder"> $ 300,000.00</span> <br>
                                <span style="font-size: 0.75rem;">Expenses</span>
                            </div>
                        </div>
                        <div class="net-fee mt-4 d-flex">
                            <i class="far fa-money-bill-alt text-success fa-lg mr-2"></i>
                            <div class="">
                                <span class="text-bolder"> $ 300,000.00</span> <br>
                                <span style="font-size: 0.75rem;">Net Fees</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-7 text-center align-items-center">
                        <h5>Put some Graph here</h5>
                    </div>
                </div>
                <hr>
                <div class="feeinfo">
                    <div class="d-flex flex-row justify-content-between">
                        <p>0 payments</p>
                        <p class="ml-2">0 part payment</p>
                        <p class="ml-2">0 oweing</p>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-lg-4">
            <div class="notice-board p-3 card1">
                <div class=" row justify-content-between">
                    <div class="ml-2">
                        <i class="far fa-calendar-check"></i> To Do
                    </div>
                    <div class="mr-2">
                        <a href="#"><i class="fas fa-plus-circle"></i></a>
                    </div>
                </div>
                <hr>

            </div>
        </div>
    </div>

    <div class="row my-3 py-3">
        
        <div class="col-lg-4">
            <div class="notice-board p-3 card1">
                <div class=" row justify-content-between">
                    <div class="ml-2">
                        <i class="fas fa-columns color-purple"></i> Notice Board
                    </div>
                    <div class="mr-2">
                        <a href="{% url 'administrator:create-notice' %}"><i
                                class="fas fa-plus-circle color-purple"></i></a>
                    </div>
                </div>
                <hr>
                {% for notice in notices %}
                <a href="#">
                    <div class="schedule-card">
                        <div class="insidebox">
                            <a href="{% url 'administrator:delete-notice-item' notice.id %}"><i class="far fa-trash-alt mr-2 text-danger"></i></a>
                            <span class="schedule-start">{{ notice.title }}</span> <br>
                            <span class="text-info">{{ notice.content }}</span> <br>
                            <div class="mt-2">
                                {% if notice.date%}
                                <span class="schedule-tag">{{ notice.date.date }} </span>
                                {% endif %}
                                <span style="font-size: 0.5rem; color: black">{{ notice.date_created | naturaltime }}
                                </span>
                            </div>
                        </div>
                    </div>
                </a>
                {% endfor %}
            </div>
        </div>

        <div class="col-lg-8 badges">
            <div class="fees-info p-3">
                <div class="academic-cal-text">
                    <i class="far fa-calendar-alt mr-3 text-warning"></i> Academic Calender
                    <hr>
                </div>
                <div>
                    som content here and more of Lorem ipsum, dolor sit amet consectetur adipisicing elit. Omnis
                    explicabo eum dolor necessitatibus repudiandae aperiam debitis minima maiores accusantium ducimus
                    dicta adipisci at, exercitationem nesciunt fugit quia, corrupti reiciendis facilis?
                </div>
            </div>
        </div>


    </div>
</div>


<br>
{% endblock %}

administrator/templates/administrator/student_list.html
{% extends '_base_dashboard.html' %}

{% load unicorn %}
{% load crispy_forms_tags %}

{% block dashboard_content %}
{% load unicorn %}

<div class="row">
    <div class="container">
        <a href="{% url 'administrator:create-student' %}">
            <div class=" m-0 info-color shadow btn btn-primary w-100 white-text text-center py-4">
                <i class="fas fa-plus-circle mr-4"></i> Register New Student
            </div>
        </a>
    </div>

    {% unicorn 'student-list' %}


</div>
{% endblock %}