accounts/urls.py
from django.urls import path
from . import views
app_name = "accounts"

urlpatterns = [
    path('generate-password/', views.generate_password, name="generate-password")
    ]

administrator/urls.py
from django.urls import path
from . import views

app_name = "administrator"


urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path("students/", views.StudentListView.as_view(), name="student-list"),
    path('students/create/', views.create_student, name="create-student"),
    path('teachers/', views.TeacherListView.as_view(), name="teacher-list"),
    path('teachers/create/', views.create_teacher, name="create-teacher"),
    path('student/<int:id>/profile/', views.student_profile, name="student-profile"),
    path('teacher/<int:id>/profile/', views.teacher_profile, name="teacher-profile"),
    path('classes/create/', views.create_klass, name="create-class"),
    path('classes/list/', views.KlassListview.as_view(), name="class-list"),
    path('classes/list/<int:pk>', views.KlassDetailView.as_view(), name="class-detail"),
    path('classes/list/<int:pk>/add-students/', views.add_students_to_class, name="add-students-to-class"),
    path('classes/list/<int:pk>/add-teacherss/', views.add_teachers_to_class, name="add-teachers-to-class"),
    path('academic-year/', views.AcademicYearListView.as_view(), name="academic-year-list"),
    path('academic-year/create/', views.create_academic_year, name="create-academic-year"),
    path('academic-year/<int:pk>/', views.AcademicYearDetailView.as_view(), name="academic-year-detail"),
    path('course/create/', views.create_course, name="create-course"),
    path('couerse/list/', views.CoursetListView.as_view(), name="course-list"),
    path('notice/create/', views.create_notice, name="create-notice"),
    path('notice/delete/<int:id>/', views.delete_notice_item, name="delete-notice-item"),

]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('django-unicorn', include('django_unicorn.urls', namespace="django_unicorn")),
    path('accounts/', include('accounts.urls',  namespace="accounts")),
    path('accounts/default/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),

    path('', include('pages.urls')),
    path('administrator/', include('administrator.urls', namespace="administrator")),
]

urlpatterns = urlpatterns + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include(debug_toolbar.urls)),
    )

pages/urls.py
from django.urls import path

from .views import HomePageView, AboutPageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about/', AboutPageView.as_view(), name='about'),
]

templates/403_csrf.html
{% extends '_base.html' %}

{% block title %}Forbidden (403){% endblock title %}

{% block content %}
<h1>Forbidden (403)</h1>
<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
<title>{% block title %}DjangoX{% endblock title %}</title>
<meta name="description" content="A framework for launching new Django projects quickly.">
<meta name="author" content="">
<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">

{% block css %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">

<link href="{% static 'css/mdb.min.css '%}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'css/base.css' %}">
{% load unicorn %}

{% unicorn_scripts %}

{% endblock %}
</head>

<body>
  {% csrf_token %}
  <main role="main">
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">
        <a href="{% url 'home' %}">DjangoX</a>
      </h5>
      <a class="p-2 text-dark" href="{% url 'about' %}">About</a>
      <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.email }}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
              <a class="dropdown-item" href="{% url 'account_change_password' %}">Change password</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'account_logout' %}">Log out</a>
            </div>
          </li>
        </ul>
        {% else %}
        <form class="form-inline ml-auto">
          <a href="{% url 'account_login' %}" class="btn btn-outline-secondary">Log in</a>
          <a href="{% url 'account_signup' %}" class="btn btn-primary ml-2">Sign up</a>
        </form>
        {% endif %}
      </nav>
    </div>
  </main>

  <div class="container">
    {% block content %}
      <p>Default content...</p>
    {% endblock content %}
  </div>

  <footer class="footer">
    <div class="container">
      <span class="text-muted">Footer...</span>
    </div>
  </footer>



  {% block javascript %}
  <!-- Bootstrap JavaScript -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
 
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>

  <!-- Project JS -->
  <script src="{% static 'js/base.js' %}"></script>

  {% endblock javascript %}

</body>
</html>

templates/_base_dashboard.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">

  <title>Material Design Bootstrap</title>
  <!-- Font Awesome -->
  <!-- Bootstrap core CSS -->
  <!-- Material Design Bootstrap -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">

  <link href="{% static 'css/mdb.min.css '%}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/main.css' %}" rel="stylesheet">
  
  <style>
    .map-container {
      overflow: hidden;
      padding-bottom: 56.25%;
      position: relative;
      height: 0;
    }

    .map-container iframe {
      left: 0;
      top: 0;
      height: 100%;
      width: 100%;
      position: absolute;
    }

    .sidebar-fixed{
      background-color: #100454;
      margin: 0;
      padding: 5px;
    }
    @media (max-width: 1199.98px){
      .sidebar-fixed.show {
        display: block;
        animation: showsidebar 0.6s ease-in;
      }
    }
    @keyframes showsidebar {
      0%{
        left: -100%;
      }
      100%{
        left: 0;
      }
      
    }

    .login-user{
      width: 100%;
      height: 60px;
      background-color: #ffffff;
      margin: 0;
      padding: 5px;
      justify-content: left;
      align-items: center;
      border-radius: 9px;
    }

    .usrinfo{
      font-weight: bolder;
      margin-left: 5px;
      text-transform: capitalize;
    }

    .admstatus{
      font-size: 0.75rem;
    }

    .list-group-item{
      background-color: #100454;
      color: white;
    }

  </style>
  {% load unicorn %}

  {% unicorn_scripts %}


</head>

<body class="bg-light">

  <!--Main Navigation-->
  <header>

    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-md navbar-light bg-light white scrolling-navbar">
      <div class="container-fluid">


        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <button class="navbar-toggler" id="side-bar-toggler"  type="button"   
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle sidebar">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

          <!-- Left -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link waves-effect" href="#">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="https://mdbootstrap.com/docs/jquery/" target="_blank">About
                MDB</a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="https://mdbootstrap.com/docs/jquery/getting-started/download/"
                target="_blank">Free
                download</a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="https://mdbootstrap.com/education/bootstrap/" target="_blank">Free
                tutorials</a>
            </li>
          </ul>

          <!-- Right -->
          <ul class="navbar-nav nav-flex-icons">
            <li class="nav-item">
              <a href="https://www.facebook.com/mdbootstrap" class="nav-link waves-effect" target="_blank">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>
            <li class="nav-item">
              <a href="https://twitter.com/MDBootstrap" class="nav-link waves-effect" target="_blank">
                <i class="fab fa-twitter"></i>
              </a>
            </li>

          </ul>

        </div>

      </div>
    </nav>
    <!-- Navbar -->

    <!-- Sidebar -->
    <div class="sidebar-fixed position-fixed" id="sidebar-fixed">

      <div class="login-user m-0 p-0 d-flex flex-row">
        <div class="usrimg">
          <img class="img-thumbnail rounded-cirle" height="70px" width="80px" src="{% if request.user.picture %}{{request.user.picture.url}}{% endif %}" alt="profile  pic">
        </div>
        <div class="usrinfo">
          <p class="m-0 p-0">{{ request.user.username }} <br>
            <span class="admstatus">
              Admin
            </span>
          </p>
        </div>
      </div>

      

      <div class="list-group list-group-flush" style="background-color: #100454;">
        <a href="{% url 'administrator:dashboard' %}" class="list-group-item active waves-effect">
          <i class="fas fa-chart-pie mr-3"></i>Dashboard
        </a>
        <a href="{% url 'administrator:student-list' %}" 
        class="list-group-item list-group-item-action waves-effect">
          <i class="fas fa-user-graduate mr-3"></i>Students</a>
        <a href="{% url 'administrator:teacher-list' %}" 
        class="list-group-item list-group-item-action waves-effect">
          <i class="fas fa-user-tie mr-3"></i>Teachers</a>
          <a href="{% url 'administrator:academic-year-list' %}" 
          class="list-group-item list-group-item-action waves-effect">
            <i class="fas fa-chalkboard-teacher mr-3"></i>Academic Years</a>
        <a href="{% url 'administrator:class-list' %}" 
        class="list-group-item list-group-item-action waves-effect">
          <i class="fas fa-chalkboard-teacher mr-3"></i>Classes</a>
        <a href="{% url 'administrator:course-list' %}" class="list-group-item list-group-item-action waves-effect">
          <i class="fas fa-book mr-3"></i>Subjects</a>
        <a href="#" class="list-group-item list-group-item-action waves-effect">
          <i class="fas fa-edit mr-3"></i>Exams</a>
        <a href="#" class="list-group-item list-group-item-action waves-effect">
          <i class="far fa-check-square mr-3"></i>Attendance</a>
        <a href="#" class="list-group-item list-group-item-action waves-effect">
          <i class="far fa-paper-plane mr-3"></i>Messages</a>
        <a href="#" class="list-group-item list-group-item-action waves-effect">
          <i class="far fa-user-circle mr-3"></i>Account</a>
        <a href="#" class="list-group-item list-group-item-action waves-effect">
          <i class="fas fa-lock mr-3"></i>Log Out</a>

          
      </div>

    </div>
    <!-- Sidebar -->

  </header>
  <!--Main Navigation-->

  <!--Main layout-->
  <main class="pt-5">
    <div class="container-fluid mt-5">
      {% block dashboard_content %}
      {% endblock %}
    </div>
  </main>
  <!--Main layout-->

  <!--Footer-->
  <footer class="page-footer text-center font-small primary-color-dark darken-2 mt-4 wow fadeIn">
    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://joetib.com" target="_blank"> Joetib.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
  <script>
    for (password_input of document.querySelectorAll("input[type='password']")) {
      password_input?.addEventListener('click', function () {
        if (confirm("Do you want an auto generated password? Password will be mailed to the account email after sign up.")) {
          fetch("{% url 'accounts:generate-password' %}").then(e => e.json()).then(data => {
            password_input.value = data['password'];
          }).catch(e => {
            alert("Error generating password");
          })
        }
      });
    }
  </script>
<script type="text/javascript" defer>
  let side_bar=document.getElementById('sidebar-fixed');
  let side_bar_toggler = document.getElementById("side-bar-toggler");

  side_bar_toggler.addEventListener('click', function(e){
    side_bar.classList.toggle('show');
     
  });
</script>
</body>

</html>