administrator/urls.py
from django.urls import path
from . import views

app_name = "administrator"


urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path("students/", views.StudentListView.as_view(), name="student-list"),
    path('students/create/', views.create_student, name="create-student"),
    path('teachers/', views.TeacherListView.as_view(), name="teacher-list"),
    path('teachers/create/', views.create_teacher, name="create-teacher"),
    path('student/<int:id>/profile/', views.student_profile, name="student-profile"),
    path('teacher/<int:id>/profile/', views.teacher_profile, name="teacher-profile"),
    path('classes/create/', views.create_klass, name="create-class"),
    path('classes/list/', views.KlassListview.as_view(), name="class-list"),
    path('classes/list/<int:pk>', views.KlassDetailView.as_view(), name="class-detail"),
    path('classes/list/<int:pk>/add-students/', views.add_students_to_class, name="add-students-to-class"),
    path('classes/list/<int:pk>/add-teacherss/', views.add_teachers_to_class, name="add-teachers-to-class"),
    path('academic-year/', views.AcademicYearListView.as_view(), name="academic-year-list"),
    path('academic-year/create/', views.create_academic_year, name="create-academic-year"),
    path('academic-year/<int:pk>/', views.AcademicYearDetailView.as_view(), name="academic-year-detail"),
    path('course/create/', views.create_course, name="create-course"),
    path('couerse/list/', views.CoursetListView.as_view(), name="course-list"),
    path('notice/create/', views.create_notice, name="create-notice"),
    path('notice/delete/<int:id>/', views.delete_notice_item, name="delete-notice-item"),

]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('django-unicorn', include('django_unicorn.urls', namespace="django_unicorn")),
    path('accounts/', include('accounts.urls',  namespace="accounts")),
    path('accounts/default/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),

    path('', include('pages.urls')),
    path('administrator/', include('administrator.urls', namespace="administrator")),
]

urlpatterns = urlpatterns + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include(debug_toolbar.urls)),
    )

pages/urls.py
from django.urls import path

from .views import HomePageView, AboutPageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('about/', AboutPageView.as_view(), name='about'),
]

unicorn/templates/unicorn/student-list.html
<div class="container">
    <!-- put component code here -->
    <div class="mt-4 bg-white p-3 shadow">
        
        <input type="text" unicorn:model.debounce-500="query_string" class="form-control"
            placeholder="Enter Name...">
    </div>
    <div class="py-5">
        <table class="table table-striped shadow bg-white">
            <thead>
                <tr>
                    <th>#</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Class</th>
                    <th>Date of birth</th>
                    <th>Profile</th>
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ student.first_name }}</td>
                    <td>{{ student.last_name }}</td>
                    <td>{{ student.get_active_class }}</td>
                    <td>{{ student.date_of_birth }}</td>
                    <td>
                        <a href="" class="btn btn-sm btn-info"><i class="fas fa-pen-square"></i></a>
                        <a href="{% url 'administrator:student-profile' student.id %}" class="btn btn-sm btn-success"><i class="fas fa-eye"></i></a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4" class="text-danger  text-center">No student found.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

unicorn/templates/unicorn/teachers-list.html
<div class="container">
    <div class="mt-3 p-3 shadow">
        
        <input type="text" unicorn:model.debounce-1000="query_string" class="form-control"
            placeholder="Enter Name...">
    </div>
    <div class="py-5">
        <table class="table table-striped shadow">
            <thead>
                <tr>
                    <th>#</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Classes</th>
                    <th>Date of birth</th>
                    <th>Profile</th>
                </tr>
            </thead>
            <tbody>
                {% for teacher in teachers %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ teacher.first_name }}</td>
                    <td>{{ teacher.last_name }}</td>
                    <td>
                        {{ teacher.get_active_class }}
                    </td>
                    <td>{{ teacher.date_of_birth }}</td>
                    <td>
                        <a href="" class="btn btn-sm btn-info"><i class="fas fa-pen-square"></i></a>
                        <a href="{% url 'administrator:teacher-profile' teacher.id %}" class="btn btn-sm btn-success"><i class="fas fa-eye"></i></a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4" class="text-danger  text-center">No Teacher found.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>